version: "3.9"

volumes:
  pgadmin: {}
  postgres_data: {}

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Data
      - ./postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    command: ../entrypoint
    env_file:
      - env.local
    ports:
      - "8000:8000"
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
        - ./app:/app
    env_file:
      - env.local
    command: ../django_migrate
    depends_on:
      - postgres
      - web
    restart: "no"
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d:rw
    depends_on:
      - web
