[tool.isort]
profile = "black"
verbose = false
py_version = "310"
skip_gitignore = true
line_length = 100
use_parentheses = true
include_trailing_comma = true
no_lines_before = "LOCALFOLDER"

[tool.black]
line-length = 100
target-version = ["py310"]
extend-exclude = """
migrations/.*
postgres_data/.*
^/.venv/
"""
